-- =====================================================================
-- Portal de Mantenimiento EPI - Esquema inicial
-- Ejecutar en: Supabase Dashboard > SQL Editor > New query > pegar > Run
-- =====================================================================

-- ============================== TABLAS ===============================

-- Catalogo de maquinas y equipos (base maestra del sistema)
create table if not exists hojas_vida (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  nombre text not null,
  area text not null,
  frecuencia_pm_meses integer,
  primer_pm date,
  activa boolean not null default true,
  foto_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

-- Registros de mantenimiento preventivo
create table if not exists preventivo (
  id uuid primary key default gen_random_uuid(),
  hoja_id uuid references hojas_vida (id) on delete set null,
  area text not null,
  fecha date not null,
  descripcion text,
  adjunto_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Solicitudes de mantenimiento correctivo
create table if not exists correctivo (
  id uuid primary key default gen_random_uuid(),
  area text not null,
  fecha date not null,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Programaciones puntuales del cronograma preventivo
create table if not exists cronograma (
  id uuid primary key default gen_random_uuid(),
  hoja_id uuid references hojas_vida (id) on delete cascade,
  fecha date not null,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Dias excluidos del cronograma
create table if not exists cronograma_excepciones (
  id uuid primary key default gen_random_uuid(),
  fecha date not null,
  motivo text,
  creado_en timestamptz not null default now()
);

-- No conformidades (formato GC-RE-009)
create table if not exists no_conformidades (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  pdf_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Horas programadas por mes y area (indicadores)
create table if not exists horas_programadas (
  id uuid primary key default gen_random_uuid(),
  periodo text not null, -- formato YYYY-MM
  area text not null,
  horas numeric not null default 0,
  unique (periodo, area)
);

-- Personal de mantenimiento
create table if not exists personal (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  cargo text,
  area text,
  cedula text,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

alter table personal add column if not exists cedula text;

-- Vinculo opcional con personal (ejecutar si la tabla ya existia)
alter table preventivo add column if not exists personal_id uuid references personal (id) on delete set null;
alter table correctivo add column if not exists personal_id uuid references personal (id) on delete set null;

-- ===================== SEGURIDAD (RLS temporal) ======================
-- Por ahora acceso abierto para desarrollar el piloto.
-- Antes de publicar la app se reemplazara por politicas con login.

alter table hojas_vida enable row level security;
alter table preventivo enable row level security;
alter table correctivo enable row level security;
alter table cronograma enable row level security;
alter table cronograma_excepciones enable row level security;
alter table no_conformidades enable row level security;
alter table horas_programadas enable row level security;
alter table personal enable row level security;

-- Matriz de conocimientos y habilidades (Mantenimiento Mecánico)
create table if not exists competencias_matriz (
  id uuid primary key default gen_random_uuid(),
  hoja text not null default 'MECANICO',
  orden integer not null,
  numero integer,
  categoria text not null,
  descripcion text not null,
  meta_d integer not null default 2 check (meta_d >= 0 and meta_d <= 4),
  experto text,
  herramienta text,
  estado_capacitacion text,
  activa boolean not null default true,
  unique (hoja, orden)
);

create table if not exists matriz_conocimiento (
  id uuid primary key default gen_random_uuid(),
  personal_id uuid not null references personal (id) on delete cascade,
  competencia_id uuid not null references competencias_matriz (id) on delete cascade,
  nivel_i integer not null default 1 check (nivel_i >= 0 and nivel_i <= 4),
  nivel_d integer not null default 2 check (nivel_d >= 0 and nivel_d <= 4),
  nivel_h integer not null default 0 check (nivel_h >= 0 and nivel_h <= 4),
  actualizado_en timestamptz not null default now(),
  unique (personal_id, competencia_id)
);

alter table competencias_matriz enable row level security;
alter table matriz_conocimiento enable row level security;

-- GH-RE-030 Permisos y horario laboral
create table if not exists horario_laboral (
  id uuid primary key default gen_random_uuid(),
  anio integer not null,
  dia_semana smallint not null check (dia_semana >= 0 and dia_semana <= 6),
  turno smallint not null default 1 check (turno >= 1 and turno <= 2),
  hora_inicio time not null,
  hora_fin time not null,
  activo boolean not null default true,
  unique (anio, dia_semana, turno)
);

create table if not exists festivos (
  id uuid primary key default gen_random_uuid(),
  anio integer not null,
  fecha date not null,
  descripcion text,
  unique (anio, fecha)
);

create table if not exists permisos_personal (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  personal_id uuid not null references personal (id) on delete cascade,
  estado text not null default 'solicitado'
    check (estado in ('borrador', 'solicitado', 'autorizado', 'en_permiso', 'cerrado')),
  pdf_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

alter table horario_laboral enable row level security;
alter table festivos enable row level security;
alter table permisos_personal enable row level security;

drop policy if exists "acceso temporal" on hojas_vida;
create policy "acceso temporal" on hojas_vida for all using (true) with check (true);

drop policy if exists "acceso temporal" on preventivo;
create policy "acceso temporal" on preventivo for all using (true) with check (true);

drop policy if exists "acceso temporal" on correctivo;
create policy "acceso temporal" on correctivo for all using (true) with check (true);

drop policy if exists "acceso temporal" on cronograma;
create policy "acceso temporal" on cronograma for all using (true) with check (true);

drop policy if exists "acceso temporal" on cronograma_excepciones;
create policy "acceso temporal" on cronograma_excepciones for all using (true) with check (true);

drop policy if exists "acceso temporal" on no_conformidades;
create policy "acceso temporal" on no_conformidades for all using (true) with check (true);

drop policy if exists "acceso temporal" on horas_programadas;
create policy "acceso temporal" on horas_programadas for all using (true) with check (true);

drop policy if exists "acceso temporal" on personal;
drop policy if exists "acceso temporal personal" on personal;
create policy "acceso temporal" on personal for all using (true) with check (true);

drop policy if exists "acceso temporal competencias_matriz" on competencias_matriz;
create policy "acceso temporal competencias_matriz" on competencias_matriz
  for all using (true) with check (true);

drop policy if exists "acceso temporal matriz_conocimiento" on matriz_conocimiento;
create policy "acceso temporal matriz_conocimiento" on matriz_conocimiento
  for all using (true) with check (true);

drop policy if exists "acceso temporal horario_laboral" on horario_laboral;
create policy "acceso temporal horario_laboral" on horario_laboral
  for all using (true) with check (true);

drop policy if exists "acceso temporal festivos" on festivos;
create policy "acceso temporal festivos" on festivos
  for all using (true) with check (true);

drop policy if exists "acceso temporal permisos_personal" on permisos_personal;
create policy "acceso temporal permisos_personal" on permisos_personal
  for all using (true) with check (true);

-- ========================= STORAGE (archivos) ========================
-- Bucket para adjuntos de preventivo (PDF/Word) y PDFs de NC generados

insert into storage.buckets (id, name, public)
values
  ('adjuntos-preventivo', 'adjuntos-preventivo', true),
  ('pdfs-nc', 'pdfs-nc', true)
on conflict (id) do nothing;

drop policy if exists "leer archivos epi" on storage.objects;
create policy "leer archivos epi" on storage.objects
  for select using (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));

drop policy if exists "subir archivos epi" on storage.objects;
create policy "subir archivos epi" on storage.objects
  for insert with check (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));

drop policy if exists "actualizar archivos epi" on storage.objects;
create policy "actualizar archivos epi" on storage.objects
  for update using (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'))
  with check (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));

drop policy if exists "borrar archivos epi" on storage.objects;
create policy "borrar archivos epi" on storage.objects
  for delete using (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));
