-- =====================================================================
-- Portal de Mantenimiento EPI - Esquema inicial
-- Ejecutar en: Supabase Dashboard > SQL Editor > New query > pegar > Run
-- =====================================================================

-- ============================== TABLAS ===============================

-- Catalogo de maquinas y equipos (base maestra del sistema)
create table if not exists hojas_vida (
  id uuid primary key default gen_random_uuid(),
  codigo text,
  nombre text not null,
  area text not null,
  frecuencia_pm_meses integer,
  primer_pm date,
  activa boolean not null default true,
  foto_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

-- Registros de mantenimiento preventivo
create table if not exists preventivo (
  id uuid primary key default gen_random_uuid(),
  hoja_id uuid references hojas_vida (id) on delete set null,
  area text not null,
  fecha date not null,
  descripcion text,
  adjunto_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Solicitudes de mantenimiento correctivo
create table if not exists correctivo (
  id uuid primary key default gen_random_uuid(),
  area text not null,
  fecha date not null,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Programaciones puntuales del cronograma preventivo
create table if not exists cronograma (
  id uuid primary key default gen_random_uuid(),
  hoja_id uuid references hojas_vida (id) on delete cascade,
  fecha date not null,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Dias excluidos del cronograma
create table if not exists cronograma_excepciones (
  id uuid primary key default gen_random_uuid(),
  fecha date not null,
  motivo text,
  creado_en timestamptz not null default now()
);

-- No conformidades (formato GC-RE-009)
create table if not exists no_conformidades (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  pdf_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Horas programadas por mes y area (indicadores)
create table if not exists horas_programadas (
  id uuid primary key default gen_random_uuid(),
  periodo text not null, -- formato YYYY-MM
  area text not null,
  horas numeric not null default 0,
  unique (periodo, area)
);

-- ===================== SEGURIDAD (RLS temporal) ======================
-- Por ahora acceso abierto para desarrollar el piloto.
-- Antes de publicar la app se reemplazara por politicas con login.

alter table hojas_vida enable row level security;
alter table preventivo enable row level security;
alter table correctivo enable row level security;
alter table cronograma enable row level security;
alter table cronograma_excepciones enable row level security;
alter table no_conformidades enable row level security;
alter table horas_programadas enable row level security;

create policy "acceso temporal" on hojas_vida for all using (true) with check (true);
create policy "acceso temporal" on preventivo for all using (true) with check (true);
create policy "acceso temporal" on correctivo for all using (true) with check (true);
create policy "acceso temporal" on cronograma for all using (true) with check (true);
create policy "acceso temporal" on cronograma_excepciones for all using (true) with check (true);
create policy "acceso temporal" on no_conformidades for all using (true) with check (true);
create policy "acceso temporal" on horas_programadas for all using (true) with check (true);

-- ========================= STORAGE (archivos) ========================
-- Bucket para adjuntos de preventivo (PDF/Word) y PDFs de NC generados

insert into storage.buckets (id, name, public)
values
  ('adjuntos-preventivo', 'adjuntos-preventivo', true),
  ('pdfs-nc', 'pdfs-nc', true)
on conflict (id) do nothing;

create policy "leer archivos epi" on storage.objects
  for select using (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));

create policy "subir archivos epi" on storage.objects
  for insert with check (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));

create policy "actualizar archivos epi" on storage.objects
  for update using (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'))
  with check (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));

create policy "borrar archivos epi" on storage.objects
  for delete using (bucket_id in ('adjuntos-preventivo', 'pdfs-nc'));
