export const SQL_MIGRACION_PERMISOS = `-- GH-RE-030 Permisos + horario laboral
alter table public.personal add column if not exists cedula text;

create table if not exists public.horario_laboral (
  id uuid primary key default gen_random_uuid(),
  anio integer not null,
  dia_semana smallint not null check (dia_semana >= 0 and dia_semana <= 6),
  turno smallint not null default 1 check (turno >= 1 and turno <= 2),
  hora_inicio time not null,
  hora_fin time not null,
  activo boolean not null default true,
  unique (anio, dia_semana, turno)
);

create table if not exists public.festivos (
  id uuid primary key default gen_random_uuid(),
  anio integer not null,
  fecha date not null,
  descripcion text,
  unique (anio, fecha)
);

create table if not exists public.permisos_personal (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  personal_id uuid not null references public.personal (id) on delete cascade,
  estado text not null default 'solicitado'
    check (estado in ('borrador', 'solicitado', 'autorizado', 'rechazado', 'cancelado', 'en_permiso', 'cerrado')),
  pdf_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

-- Si la tabla ya existía, actualiza el check de estados:
alter table public.permisos_personal drop constraint if exists permisos_personal_estado_check;
alter table public.permisos_personal
  add constraint permisos_personal_estado_check
  check (estado in ('borrador', 'solicitado', 'autorizado', 'rechazado', 'cancelado', 'en_permiso', 'cerrado'));

alter table public.horario_laboral enable row level security;
alter table public.festivos enable row level security;
alter table public.permisos_personal enable row level security;

drop policy if exists "acceso temporal horario_laboral" on public.horario_laboral;
create policy "acceso temporal horario_laboral" on public.horario_laboral
  for all using (true) with check (true);

drop policy if exists "acceso temporal festivos" on public.festivos;
create policy "acceso temporal festivos" on public.festivos
  for all using (true) with check (true);

drop policy if exists "acceso temporal permisos_personal" on public.permisos_personal;
create policy "acceso temporal permisos_personal" on public.permisos_personal
  for all using (true) with check (true);
`;

/** Estados válidos actuales (rechazado + cancelado). Ejecutar si falla el check de estado. */
export const SQL_MIGRACION_PERMISO_CANCELADO = `-- Actualiza check de estados en permisos_personal (rechazado + cancelado)
do $$
declare
  r record;
begin
  for r in
    select con.conname
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
    where nsp.nspname = 'public'
      and rel.relname = 'permisos_personal'
      and con.contype = 'c'
      and pg_get_constraintdef(con.oid) ilike '%estado%'
  loop
    execute format('alter table public.permisos_personal drop constraint if exists %I', r.conname);
  end loop;
end $$;

alter table public.permisos_personal
  add constraint permisos_personal_estado_check
  check (estado in (
    'borrador',
    'solicitado',
    'autorizado',
    'rechazado',
    'cancelado',
    'en_permiso',
    'cerrado'
  ));
`;

/** Alias: misma migración completa de estados. */
export const SQL_MIGRACION_PERMISO_RECHAZADO = SQL_MIGRACION_PERMISO_CANCELADO;

export function faltaTablaPermisos(mensaje: string): boolean {
  return /permisos_personal|horario_laboral|festivos|schema cache|relation.*does not exist/i.test(
    mensaje,
  );
}
