-- GC-RE-001 Acciones de mejora
create table if not exists acciones_mejora (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  pdf_url text,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

alter table acciones_mejora enable row level security;

drop policy if exists "acceso temporal acciones_mejora" on acciones_mejora;
create policy "acceso temporal acciones_mejora" on acciones_mejora
  for all using (true) with check (true);
