-- GC-RE-027 Gestión del cambio
create table if not exists gestion_cambio (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

alter table gestion_cambio enable row level security;

drop policy if exists "acceso temporal gestion_cambio" on gestion_cambio;
create policy "acceso temporal gestion_cambio" on gestion_cambio
  for all using (true) with check (true);

-- Si ya aplicaste auth_usuarios.sql, refuerza con roles:
-- drop policy if exists "acceso temporal gestion_cambio" on gestion_cambio;
-- select public._aplicar_rls_tabla('gestion_cambio');

select 'Tabla gestion_cambio (GC-RE-027) lista.' as resultado;
