import { supabase } from "../../services/supabase";
import type { RegistroGc027, RegistroGc027Datos } from "./gcre027Types";

const TABLA = "gestion_cambio";

export async function listarGestionCambio(): Promise<RegistroGc027[]> {
  const { data, error } = await supabase
    .from(TABLA)
    .select("*")
    .order("numero", { ascending: false });
  if (error) throw new Error(error.message);
  return (data ?? []) as RegistroGc027[];
}

export async function guardarGestionCambio(
  datos: RegistroGc027Datos,
  editandoId: string | null,
): Promise<RegistroGc027> {
  if (editandoId) {
    const { data, error } = await supabase
      .from(TABLA)
      .update({ datos })
      .eq("id", editandoId)
      .select()
      .single();
    if (error) throw new Error(error.message);
    return data as RegistroGc027;
  }

  const { data, error } = await supabase.from(TABLA).insert({ datos }).select().single();
  if (error) throw new Error(error.message);
  return data as RegistroGc027;
}

export async function eliminarGestionCambio(id: string): Promise<void> {
  const { error } = await supabase.from(TABLA).delete().eq("id", id);
  if (error) throw new Error(error.message);
}

export function esErrorTablaGestionCambio(mensaje: string): boolean {
  return /gestion_cambio|schema cache|does not exist|Could not find the table/i.test(mensaje);
}

export const SQL_MIGRACION_GESTION_CAMBIO = `-- GC-RE-027 Gestión del cambio
create table if not exists gestion_cambio (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  datos jsonb not null default '{}',
  creado_en timestamptz not null default now()
);

alter table gestion_cambio enable row level security;

drop policy if exists "acceso temporal gestion_cambio" on gestion_cambio;
create policy "acceso temporal gestion_cambio" on gestion_cambio
  for all using (true) with check (true);

select 'Tabla gestion_cambio (GC-RE-027) lista.' as resultado;
`;
